### ISSUE TITLE
Notes on update v1.0.12

### ISSUE THREAD

**Issue by Gruce** [EnabApp/Utilities#5]
Hello, @i1Zeus @william-iq397 

Great work guys, keep going!

Some notes on the update of utilities v1.0.12

**Calculator Notes**

- [x] Buttons have fixed size which when it gets maximized button sized are not getting fluid size.
- [x] Screen `2xl` not showing history side. while on `xl` it works fine. History side need user interface improvements. Modal is not a good UX maybe if it shown on the top of button or instead of it. I think it could be better.
- [x] Fluid design applied on width but not on height. There is space between `bottom bar` and last row of button.
- [x] It's better if `Esc key` clear the input of the calculator, this could improve ux.
- [x] Maximized has same limit number as regular size.
- [x] What about adding comma separator (, ) for numbers, e.g. (1,530,000).

**Todo Notes**

- [x] [ISSUE] ref is not defined.
- [x] What about this idea. The regular size shows all tasks (completed and not completed) and when size gets enough size it could be splits into two sections one for completed and one for archived. And maybe some counts on completed tasks and not completed tasks?

Thank you for your amazing work

**Comment by i1Zeus** [comment]
All the mentioned above, have been fixed / add and updated. 
please stay tuned for our next release  
thanks for your advise❤👍
